-- ============================================================================
-- CREATOR CLUB - WEEKLY SUCCESS REPORTS SCHEMA
-- ============================================================================
-- Migration: 017_weekly_success_reports.sql
-- Created: 2026-01-11
--
-- This migration creates the table for storing automated weekly success reports
-- generated by the AI Success Manager for creators.
--
-- Features:
-- - Stores AI-generated reports with full content
-- - Tracks week boundaries for each report
-- - Links to creator profiles for multi-tenant isolation
-- - Supports manual and automated (cron) generation
-- ============================================================================

-- ============================================================================
-- SECTION 1: CREATE TABLE
-- ============================================================================

CREATE TABLE public.weekly_success_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Creator reference (profile.id, NOT auth.users.id)
  creator_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,

  -- Report content (markdown formatted by AI)
  report_content TEXT NOT NULL,

  -- Report metadata
  generated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  week_start DATE NOT NULL,
  week_end DATE NOT NULL,

  -- Tracking data used for generation (for audit/debugging)
  students_analyzed INTEGER DEFAULT 0,
  at_risk_count INTEGER DEFAULT 0,

  -- Generation source (manual = user clicked button, automated = cron job)
  generation_source TEXT DEFAULT 'manual' CHECK (generation_source IN ('manual', 'automated')),

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ============================================================================
-- SECTION 2: INDEXES
-- ============================================================================

-- Primary query pattern: get reports for a specific creator
CREATE INDEX weekly_success_reports_creator_id_idx ON public.weekly_success_reports(creator_id);

-- Query pattern: get reports ordered by date
CREATE INDEX weekly_success_reports_generated_at_idx ON public.weekly_success_reports(generated_at DESC);

-- Query pattern: get reports for a specific week
CREATE INDEX weekly_success_reports_week_idx ON public.weekly_success_reports(week_start, week_end);

-- Composite index for common query: creator's reports by date
CREATE INDEX weekly_success_reports_creator_date_idx ON public.weekly_success_reports(creator_id, generated_at DESC);

-- ============================================================================
-- SECTION 3: ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE public.weekly_success_reports ENABLE ROW LEVEL SECURITY;

-- Creators can view their own reports
CREATE POLICY "Creators can view own reports" ON public.weekly_success_reports
  FOR SELECT
  USING (creator_id = get_my_profile_id());

-- Creators can insert their own reports (for manual generation)
CREATE POLICY "Creators can create own reports" ON public.weekly_success_reports
  FOR INSERT
  WITH CHECK (creator_id = get_my_profile_id());

-- Service role can insert reports (for automated cron jobs)
-- Note: Service role bypasses RLS by default, so no explicit policy needed

-- Creators can delete their own reports (optional cleanup)
CREATE POLICY "Creators can delete own reports" ON public.weekly_success_reports
  FOR DELETE
  USING (creator_id = get_my_profile_id());

-- ============================================================================
-- SECTION 4: TRIGGER FOR UPDATED_AT
-- ============================================================================

CREATE TRIGGER set_weekly_success_reports_updated_at
  BEFORE UPDATE ON public.weekly_success_reports
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- SECTION 5: COMMENTS
-- ============================================================================

COMMENT ON TABLE public.weekly_success_reports IS 'Stores AI-generated weekly success reports for creators';
COMMENT ON COLUMN public.weekly_success_reports.creator_id IS 'References profiles.id (NOT auth.users.id)';
COMMENT ON COLUMN public.weekly_success_reports.report_content IS 'AI-generated report in markdown format';
COMMENT ON COLUMN public.weekly_success_reports.week_start IS 'Start date of the reporting week (inclusive)';
COMMENT ON COLUMN public.weekly_success_reports.week_end IS 'End date of the reporting week (inclusive)';
COMMENT ON COLUMN public.weekly_success_reports.generation_source IS 'How the report was triggered: manual (button click) or automated (cron)';
